# Generated by Django 4.1.5 on 2023-01-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_author_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='is_subscriber',
            field=models.BooleanField(default=False, verbose_name='Подписчик'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('tank', 'Танки'), ('healer', 'Хилы'), ('dd', 'ДД'), ('trader', 'Торговцы'), ('master', 'Гилдмастеры'), ('quest', 'Квестгиверы'), ('smith', 'Кузнецы'), ('skinner', 'Кожевники'), ('potion', 'Зельевары'), ('caster', 'Мастера заклинаний')], default='tank', max_length=8, unique=True, verbose_name='Категория'),
        ),
    ]
