# Generated by Django 4.1.5 on 2023-02-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_author_is_subscriber_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('cards', 'Карты'), ('decks', 'Колоды'), ('heroes', 'Герои'), ('tactic', 'Тактика'), ('strategy', 'Стратегия'), ('mage', 'Маг'), ('warlock', 'Чернокнижник'), ('paladin', 'Паладин')], default='tank', max_length=8, unique=True, verbose_name='Категория'),
        ),
    ]
